# Generated CI/CD Pipeline YAML
# This YAML is compatible with GitHub Actions

# Pipeline: default_pipeline
name: default_pipeline

on:
  workflow_dispatch:

jobs:
  build_test:
    # Build and test the instalation
    runs-on: ubuntu-latest
    steps:
            - name: command_33037
              uses: actions/checkout@v4
            - name: install dependencies
              uses: actions/checkout@v3
              with:
                        Java-version:'11'
                        distribution:'temurin'
            - name: build and test
              run: mvn -B verify          || True
