name: tutorial_pipeline_ga
on:
  workflow_dispatch:
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install dep
        run: pip install -r requirements.txt
      - name: check version
        run: python3 --version
